// packages/vue/src/components/Dialog.vue
<script setup lang="ts">
import { onBeforeUnmount, watch } from "vue";
import Window from "./Window.vue";

const props = defineProps<{
  open: boolean;
  title: string;
  width?: number | string;
  closeOnBackdrop?: boolean;
}>();
const emit = defineEmits<{ close: [] }>();

function onKey(event: KeyboardEvent) {
  if (event.key === "Escape") emit("close");
}

watch(
  () => props.open,
  (open) => {
    if (open) document.addEventListener("keydown", onKey);
    else document.removeEventListener("keydown", onKey);
  },
  { immediate: true },
);
onBeforeUnmount(() => document.removeEventListener("keydown", onKey));
</script>

<template>
  <div
    v-if="open"
    class="retro-dialog-backdrop"
    @pointerdown="(event) => {
      if ((closeOnBackdrop ?? true) && event.target === event.currentTarget) emit('close');
    }"
  >
    <div role="dialog" aria-modal="true" :aria-label="title" class="retro-dialog-wrap">
      <Window :title="title" :width="width" class="retro-dialog" :draggable="false">
        <slot />
      </Window>
    </div>
  </div>
</template>

// packages/react/src/components/Dialog.tsx
import { useEffect } from "react";
import type { ReactNode } from "react";
import { Window } from "./Chrome";
import { cx } from "../cx";

export function Dialog({
  open,
  title,
  onClose,
  closeOnBackdrop = true,
  width,
  className,
  children,
}: {
  open: boolean;
  title: string;
  onClose: () => void;
  closeOnBackdrop?: boolean;
  width?: number | string;
  className?: string;
  children?: ReactNode;
}) {
  useEffect(() => {
    if (!open) return;
    function onKey(event: KeyboardEvent) {
      if (event.key === "Escape") onClose();
    }
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      className="retro-dialog-backdrop"
      onPointerDown={(event) => {
        if (closeOnBackdrop && event.target === event.currentTarget) onClose();
      }}
    >
      <div className="retro-dialog-wrap" role="dialog" aria-modal="true" aria-label={title}>
        <Window
          title={title}
          width={width}
          className={cx("retro-dialog", className)}
          draggable={false}
        >
          {children}
        </Window>
      </div>
    </div>
  );
}
