// packages/svelte/src/lib/Desktop.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";
  import type { RetroTheme } from "@retro-ui/themes";
  import { RETRO_THEME_KEY } from "../context";

  let {
    class: className = "",
    children,
    taskbar,
  }: { class?: string; children?: Snippet; taskbar?: Snippet } = $props();

  const theme = getContext<RetroTheme | undefined>(RETRO_THEME_KEY);
</script>

<div class="retro-desktop{className ? ` ${className}` : ""}" data-pattern={theme?.desktopPattern}>
  <div class="retro-desktop-stage">{@render children?.()}</div>
  {#if taskbar}{@render taskbar()}{/if}
</div>

// packages/vue/src/components/Desktop.vue
<script setup lang="ts">
import { computed, inject, type ComputedRef } from "vue";
import type { RetroTheme } from "@retro-ui/themes";
import { RETRO_THEME_KEY } from "../context";

const theme = inject<ComputedRef<RetroTheme>>(RETRO_THEME_KEY);
const pattern = computed(() => theme?.value.desktopPattern);
</script>

<template>
  <div class="retro-desktop" :data-pattern="pattern">
    <div class="retro-desktop-stage">
      <slot />
    </div>
    <slot name="taskbar" />
  </div>
</template>
