// packages/svelte/src/lib/MenuBar.svelte
<script lang="ts">
  let { items }: { items: Array<{ label: string; onClick?: () => void }> } = $props();
</script>

<nav class="retro-menubar" aria-label="Menu bar">
  {#each items as item (item.label)}
    <button type="button" class="retro-menuitem" onclick={item.onClick}>{item.label}</button>
  {/each}
</nav>

// packages/vue/src/components/MenuBar.vue
<script setup lang="ts">
defineProps<{ items: Array<{ label: string; onClick?: () => void }> }>();
</script>

<template>
  <nav class="retro-menubar" aria-label="Menu bar">
    <button
      v-for="item in items"
      :key="item.label"
      type="button"
      class="retro-menuitem"
      @click="item.onClick"
    >
      {{ item.label }}
    </button>
  </nav>
</template>
