// packages/react/src/components/Menu.tsx
import { useEffect, useRef, useState } from "react";
import { cx } from "../cx";

export interface MenuItem {
  label: string;
  onClick?: () => void;
  disabled?: boolean;
}

export function Menu({
  label,
  items,
  className,
}: {
  label: string;
  items: MenuItem[];
  className?: string;
}) {
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!open) return;
    function onDocPointerDown(event: PointerEvent) {
      if (!rootRef.current?.contains(event.target as Node)) setOpen(false);
    }
    function onKey(event: KeyboardEvent) {
      if (event.key === "Escape") setOpen(false);
    }
    document.addEventListener("pointerdown", onDocPointerDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("pointerdown", onDocPointerDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  return (
    <div className={cx("retro-menu", className)} ref={rootRef}>
      <button
        type="button"
        className="retro-button"
        aria-haspopup="menu"
        aria-expanded={open}
        onClick={() => setOpen((value) => !value)}
      >
        {label}
      </button>
      {open ? (
        <div className="retro-menu-popup" role="menu">
          {items.map((item) => (
            <button
              key={item.label}
              type="button"
              role="menuitem"
              disabled={item.disabled}
              onClick={() => {
                setOpen(false);
                item.onClick?.();
              }}
            >
              {item.label}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
}

// packages/vue/src/components/Menu.vue
<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from "vue";

defineProps<{
  label: string;
  items: Array<{ label: string; onClick?: () => void; disabled?: boolean }>;
}>();

const open = ref(false);
const root = ref<HTMLElement | null>(null);

function onDocPointerDown(event: PointerEvent) {
  if (!root.value?.contains(event.target as Node)) open.value = false;
}
function onKey(event: KeyboardEvent) {
  if (event.key === "Escape") open.value = false;
}

watch(open, (value) => {
  if (value) {
    document.addEventListener("pointerdown", onDocPointerDown);
    document.addEventListener("keydown", onKey);
  } else {
    document.removeEventListener("pointerdown", onDocPointerDown);
    document.removeEventListener("keydown", onKey);
  }
});
onBeforeUnmount(() => {
  document.removeEventListener("pointerdown", onDocPointerDown);
  document.removeEventListener("keydown", onKey);
});
</script>

<template>
  <div ref="root" class="retro-menu">
    <button
      type="button"
      class="retro-button"
      aria-haspopup="menu"
      :aria-expanded="open"
      @click="open = !open"
    >
      {{ label }}
    </button>
    <div v-if="open" class="retro-menu-popup" role="menu">
      <button
        v-for="item in items"
        :key="item.label"
        type="button"
        role="menuitem"
        :disabled="item.disabled"
        @click="
          open = false;
          item.onClick?.();
        "
      >
        {{ item.label }}
      </button>
    </div>
  </div>
</template>
