// packages/svelte/src/lib/Radio.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";

  let {
    label,
    class: className = "",
    ...rest
  }: HTMLInputAttributes & { label: string; class?: string } = $props();
</script>

<label class="retro-radio{className ? ` ${className}` : ""}">
  <input type="radio" {...rest} />
  <span>{label}</span>
</label>

// packages/vue/src/components/Radio.vue
<script setup lang="ts">
import { useAttrs } from "vue";

defineOptions({ inheritAttrs: false });
defineProps<{ label: string }>();
const attrs = useAttrs();
</script>

<template>
  <label class="retro-radio">
    <input v-bind="attrs" type="radio" />
    <span>{{ label }}</span>
  </label>
</template>
