// packages/svelte/src/lib/Table.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    columns,
    rows,
  }: { columns: string[]; rows: Array<Array<string | Snippet>> } = $props();
</script>

<div class="retro-table-wrap">
  <table class="retro-table">
    <thead>
      <tr>
        {#each columns as column (column)}<th>{column}</th>{/each}
      </tr>
    </thead>
    <tbody>
      {#each rows as row, index (index)}
        <tr data-selected={index === 0}>
          {#each row as cell, cellIndex (cellIndex)}
            <td>
              {#if typeof cell === "string"}{cell}{:else}{@render cell()}{/if}
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// packages/vue/src/components/Table.vue
<script setup lang="ts">
import type { VNode } from "vue";

defineProps<{
  columns: string[];
  rows: Array<Array<string | VNode>>;
}>();
</script>

<template>
  <div class="retro-table-wrap">
    <table class="retro-table">
      <thead>
        <tr>
          <th v-for="column in columns" :key="column">{{ column }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, index) in rows" :key="index" :data-selected="index === 0">
          <td v-for="(cell, cellIndex) in row" :key="cellIndex">
            <component :is="() => cell" />
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
