// packages/vue/src/components/Menu.vue
<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from "vue";

defineProps<{
  label: string;
  items: Array<{ label: string; onClick?: () => void; disabled?: boolean }>;
}>();

const open = ref(false);
const root = ref<HTMLElement | null>(null);

function onDocPointerDown(event: PointerEvent) {
  if (!root.value?.contains(event.target as Node)) open.value = false;
}
function onKey(event: KeyboardEvent) {
  if (event.key === "Escape") open.value = false;
}

watch(open, (value) => {
  if (value) {
    document.addEventListener("pointerdown", onDocPointerDown);
    document.addEventListener("keydown", onKey);
  } else {
    document.removeEventListener("pointerdown", onDocPointerDown);
    document.removeEventListener("keydown", onKey);
  }
});
onBeforeUnmount(() => {
  document.removeEventListener("pointerdown", onDocPointerDown);
  document.removeEventListener("keydown", onKey);
});
</script>

<template>
  <div ref="root" class="retro-menu">
    <button
      type="button"
      class="retro-button"
      aria-haspopup="menu"
      :aria-expanded="open"
      @click="open = !open"
    >
      {{ label }}
    </button>
    <div v-if="open" class="retro-menu-popup" role="menu">
      <button
        v-for="item in items"
        :key="item.label"
        type="button"
        role="menuitem"
        :disabled="item.disabled"
        @click="
          open = false;
          item.onClick?.();
        "
      >
        {{ item.label }}
      </button>
    </div>
  </div>
</template>

// packages/svelte/src/lib/Menu.svelte
<script lang="ts">
  let {
    label,
    items,
  }: {
    label: string;
    items: Array<{ label: string; onClick?: () => void; disabled?: boolean }>;
  } = $props();

  let open = $state(false);
  let root: HTMLElement | undefined = $state();

  function onDocPointerDown(event: PointerEvent) {
    if (!root?.contains(event.target as Node)) open = false;
  }

  function onKey(event: KeyboardEvent) {
    if (event.key === "Escape") open = false;
  }

  $effect(() => {
    if (!open) return;
    document.addEventListener("pointerdown", onDocPointerDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("pointerdown", onDocPointerDown);
      document.removeEventListener("keydown", onKey);
    };
  });
</script>

<div bind:this={root} class="retro-menu">
  <button
    type="button"
    class="retro-button"
    aria-haspopup="menu"
    aria-expanded={open}
    onclick={() => (open = !open)}
  >
    {label}
  </button>
  {#if open}
    <div class="retro-menu-popup" role="menu">
      {#each items as item (item.label)}
        <button
          type="button"
          role="menuitem"
          disabled={item.disabled}
          onclick={() => {
            open = false;
            item.onClick?.();
          }}
        >
          {item.label}
        </button>
      {/each}
    </div>
  {/if}
</div>
