// packages/vue/src/components/RetroProvider.vue
<script setup lang="ts">
import { computed, provide, type ComputedRef } from "vue";
import { getTheme, themeToCssVars, type RetroTheme } from "@retro-ui/themes";
import { RETRO_THEME_KEY } from "../context";

const props = defineProps<{ theme: RetroTheme | string }>();

const resolved = computed<RetroTheme>(() =>
  typeof props.theme === "string" ? getTheme(props.theme) : props.theme,
);

provide<ComputedRef<RetroTheme>>(RETRO_THEME_KEY, resolved);

const cssVars = computed<Record<string, string>>(() => themeToCssVars(resolved.value));
</script>

<template>
  <div
    class="retro-root"
    :data-theme="resolved.id"
    :data-engine="resolved.engine"
    :data-controls="resolved.controls"
    :style="cssVars"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/lib/RetroProvider.svelte
<script lang="ts">
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";
  import { getTheme, themeToCssVars, type RetroTheme } from "@retro-ui/themes";
  import { RETRO_THEME_KEY } from "../context";

  let {
    theme,
    class: className = "",
    children,
  }: {
    theme: RetroTheme | string;
    class?: string;
    children?: Snippet;
  } = $props();

  const resolved: RetroTheme = typeof theme === "string" ? getTheme(theme) : theme;
  setContext(RETRO_THEME_KEY, resolved);

  const styleText = $derived(
    Object.entries(themeToCssVars(resolved))
      .map(([key, value]) => `${key}: ${value};`)
      .join(" "),
  );
</script>

<div
  class="retro-root {className}"
  data-theme={resolved.id}
  data-engine={resolved.engine}
  data-controls={resolved.controls}
  style={styleText}
>
  {@render children?.()}
</div>
