// packages/vue/src/components/Tabs.vue
<script setup lang="ts">
import { ref, type VNode } from "vue";

const props = defineProps<{
  tabs: Array<{ id: string; label: string; content?: VNode }>;
  defaultTab?: string;
}>();

const active = ref(props.defaultTab ?? props.tabs[0]?.id);
</script>

<template>
  <div class="retro-tabs">
    <div class="retro-tablist" role="tablist">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        role="tab"
        class="retro-tab"
        :aria-selected="tab.id === active"
        @click="active = tab.id"
      >
        {{ tab.label }}
      </button>
    </div>
    <template v-for="tab in tabs" :key="tab.id">
      <div v-if="tab.id === active" role="tabpanel" class="retro-tabpanel">
        <component :is="() => tab.content" />
      </div>
    </template>
  </div>
</template>

// packages/svelte/src/lib/Tabs.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    tabs,
    defaultTab,
  }: { tabs: Array<{ id: string; label: string; content?: Snippet }>; defaultTab?: string } =
    $props();

  let active = $state(defaultTab ?? tabs[0]?.id);
</script>

<div class="retro-tabs">
  <div class="retro-tablist" role="tablist">
    {#each tabs as tab (tab.id)}
      <button
        type="button"
        role="tab"
        class="retro-tab"
        aria-selected={tab.id === active}
        onclick={() => (active = tab.id)}
      >
        {tab.label}
      </button>
    {/each}
  </div>
  {#each tabs as tab (tab.id)}
    {#if tab.id === active}
      <div role="tabpanel" class="retro-tabpanel">{@render tab.content?.()}</div>
    {/if}
  {/each}
</div>
