// packages/vue/src/components/Window.vue
<script setup lang="ts">
import { computed, inject, ref, type ComputedRef, type CSSProperties } from "vue";
import type { RetroTheme } from "@retro-ui/themes";
import { RETRO_THEME_KEY } from "../context";
import { bumpWindowStack } from "../windowStack";
import TitleButton from "./TitleButton.vue";

const props = withDefaults(
  defineProps<{
    title: string;
    active?: boolean;
    width?: number | string;
    draggable?: boolean;
  }>(),
  { active: true, draggable: true },
);

const theme = inject<ComputedRef<RetroTheme>>(RETRO_THEME_KEY);
const showControls = computed(() => theme?.value.controls !== "none");
const isMac = computed(() => theme?.value.controls === "mac");

const el = ref<HTMLElement | null>(null);
const offset = ref({ x: 0, y: 0 });
let dragInfo: {
  pointerId: number;
  startX: number;
  startY: number;
  baseX: number;
  baseY: number;
} | null = null;

function bringToFront() {
  if (el.value) el.value.style.zIndex = String(bumpWindowStack());
}

function onTitlePointerDown(event: PointerEvent) {
  if (!props.draggable || event.button !== 0) return;
  if ((event.target as HTMLElement).closest(".retro-titlebar-controls button")) return;
  bringToFront();
  dragInfo = {
    pointerId: event.pointerId,
    startX: event.clientX,
    startY: event.clientY,
    baseX: offset.value.x,
    baseY: offset.value.y,
  };
  try {
    (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId);
  } catch {
    /* pointer capture unavailable — drag ends on release anyway */
  }
}

function onTitlePointerMove(event: PointerEvent) {
  if (!dragInfo || dragInfo.pointerId !== event.pointerId) return;
  offset.value = {
    x: dragInfo.baseX + event.clientX - dragInfo.startX,
    y: dragInfo.baseY + event.clientY - dragInfo.startY,
  };
}

function endDrag(event: PointerEvent) {
  if (dragInfo?.pointerId === event.pointerId) dragInfo = null;
}

const windowStyle = computed<CSSProperties>(() => ({
  ...(props.width != null ? { width: props.width } : {}),
  ...(props.draggable
    ? { transform: `translate(${offset.value.x}px, ${offset.value.y}px)` }
    : {}),
}));
</script>

<template>
  <section
    ref="el"
    class="retro-window"
    :data-active="active"
    :data-draggable="draggable"
    :style="windowStyle"
    @pointerdown="bringToFront"
  >
    <header
      class="retro-titlebar"
      @pointerdown="onTitlePointerDown"
      @pointermove="onTitlePointerMove"
      @pointerup="endDrag"
      @pointercancel="endDrag"
    >
      <div v-if="showControls && isMac" class="retro-titlebar-controls">
        <TitleButton kind="close" />
        <TitleButton kind="min" />
        <TitleButton kind="max" />
      </div>
      <div class="retro-titlebar-title">{{ title }}</div>
      <div v-if="showControls && !isMac" class="retro-titlebar-controls">
        <TitleButton kind="min" />
        <TitleButton kind="max" />
        <TitleButton kind="close" />
      </div>
    </header>
    <div class="retro-window-body">
      <slot />
    </div>
    <div v-if="$slots.status" class="retro-window-status">
      <slot name="status" />
    </div>
  </section>
</template>

// packages/svelte/src/lib/Window.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";
  import type { RetroTheme } from "@retro-ui/themes";
  import { RETRO_THEME_KEY } from "../context";
  import { bumpWindowStack } from "../windowStack";
  import TitleButton from "./TitleButton.svelte";

  let {
    title,
    active = true,
    status,
    width,
    draggable = true,
    class: className = "",
    style,
    children,
  }: {
    title: string;
    active?: boolean;
    status?: Snippet;
    width?: number | string;
    draggable?: boolean;
    class?: string;
    style?: string;
    children?: Snippet;
  } = $props();

  const theme = getContext<RetroTheme | undefined>(RETRO_THEME_KEY);
  const showControls = theme?.controls !== "none";

  let el: HTMLElement | undefined = $state();
  let offset = $state({ x: 0, y: 0 });
  let dragInfo: {
    pointerId: number;
    startX: number;
    startY: number;
    baseX: number;
    baseY: number;
  } | null = null;

  function bringToFront() {
    if (el) el.style.zIndex = String(bumpWindowStack());
  }

  function onTitlePointerDown(event: PointerEvent) {
    if (!draggable || event.button !== 0) return;
    if ((event.target as HTMLElement).closest(".retro-titlebar-controls button")) return;
    bringToFront();
    dragInfo = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startY: event.clientY,
      baseX: offset.x,
      baseY: offset.y,
    };
    try {
      (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId);
    } catch {
      /* pointer capture unavailable — drag ends on release anyway */
    }
  }

  function onTitlePointerMove(event: PointerEvent) {
    if (!dragInfo || dragInfo.pointerId !== event.pointerId) return;
    offset = {
      x: dragInfo.baseX + event.clientX - dragInfo.startX,
      y: dragInfo.baseY + event.clientY - dragInfo.startY,
    };
  }

  function endDrag(event: PointerEvent) {
    if (dragInfo?.pointerId === event.pointerId) dragInfo = null;
  }

  const styleText = $derived(
    [
      width ? `width: ${typeof width === "number" ? `${width}px` : width}` : "",
      draggable ? `transform: translate(${offset.x}px, ${offset.y}px)` : "",
      style ?? "",
    ]
      .filter(Boolean)
      .join("; "),
  );
</script>

<section
  bind:this={el}
  class={`retro-window${className ? ` ${className}` : ""}`}
  data-active={active}
  data-draggable={draggable}
  style={styleText}
  onpointerdown={bringToFront}
>
  <header
    class="retro-titlebar"
    onpointerdown={onTitlePointerDown}
    onpointermove={onTitlePointerMove}
    onpointerup={endDrag}
    onpointercancel={endDrag}
  >
    {#if showControls && theme?.controls === "mac"}
      <div class="retro-titlebar-controls">
        <TitleButton kind="close" />
        <TitleButton kind="min" />
        <TitleButton kind="max" />
      </div>
    {/if}
    <div class="retro-titlebar-title">{title}</div>
    {#if showControls && theme?.controls !== "mac"}
      <div class="retro-titlebar-controls">
        <TitleButton kind="min" />
        <TitleButton kind="max" />
        <TitleButton kind="close" />
      </div>
    {/if}
  </header>
  <div class="retro-window-body">{@render children?.()}</div>
  {#if status}<div class="retro-window-status">{@render status()}</div>{/if}
</section>
